### ISSUE TITLE
CustomLocalization mod xnb file

### ISSUE THREAD

**Issue by wally232** [ZaneYork/SDV_CustomLocalization#1]
The game was played without changing the localization code.

It all works well.
But there are some things that are not applicable.

The files below are not applied.

The other files were well applied.

Cursors.ko-KR.xnb
Cursors.xnb
MobileAtlas_manually_made.xnb
accessories.xnb
hairstyles.xnb
furniture.xnb
furniture.ko-KR.xnb

=================================
The following Korean-related files have also been applied:
All other Korean-related files are also well applicable.

All but the above files apply.

spring_outdoorsTileSheet.ko-KR.xnb
spring_twon.ko-KR.xnb
TitleButtons.ko-KR.xnb

**Comment by ZaneYork** [comment]
Fixed in latest release



---Original---

**Comment by wally232** [comment]
Thank you very much.
I installed the latest SMAPI.

Most of the non-applicable things have been solved.

However, there is an xnb file that has not yet been resolved.

Files below in the LooseSprites folder in Content
MobileAtlas_manually_made.xnb

Files below in the Fonts folder on the Content
Korean.xnb
Korean_00 to Korean_11.xnb

The above file is still not resolved.

**Comment by ZaneYork** [comment]
Please send the fonts and config.json to me, I'll check it



---Original---
